dependencies:
- alias: expose
  name: exposecontroller
  repository: '@chartmuseum.jenkins-x.io'
  version: 2.3.92
- alias: cleanup
  name: exposecontroller
  repository: '@chartmuseum.jenkins-x.io'
  version: 2.3.92
- alias: preview
  name: scooters
  repository: file://../scooters
  version: 0.0.3
