
version: '3.1'
services:
    jenkins:
        container_name: jenkins-master
        ports:
            - '8081:8081'
            - '50001:50001'
        image: jenkins-master
    jenkins-slave:
        container_name: jenkins-slave
        restart: always
        environment:
            - 'JENKINS_URL=http://jenkins:8081'
        image: jenkins-slave
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - jenkins